### ISSUE TITLE
Request for technical stack info

### ISSUE THREAD

**Issue by pierreyvesbaloche** [dglaude/circuitpython_phat_on_pico#1]
Hello 👋, 

At the time of writing, concerning the scroll-phat-hd example, the i2c init raises an error as no pull-up resistor is detected between SDA and SCL.

Failing tests were made with:
- RedRobotic Rev. 0.3 board 
- CircuitPython 6.2.0

Did you modify the "hardware" you get it to work?
Could you share the curcuitpython version you used also? 

Thanks ;)

**Comment by dglaude** [comment]
A Raspberry Pi Zero (and other) do have build-in Pull-Up resistor on SDA/SCL lines.
So many HAT/pHAT do not have one and rely on that.

MCU running CircuitPython, such as Feather or the Pico do not have such Pull-Up because many pin can be used to do I2C.
The RedRobotic board I have does also not have those Pull-Up and would produce the same error message that is valid.

I did not modify my hardware, and I expect future version of the board to have such Pull-Up as I notified the maker.
What I do is to "duplicate" the 40 pin bus and put another board that has Pull-Up.

On this video, you can see that it is working, but notice the big distance from and additional pins:
https://twitter.com/DavidGlaude/status/1369422737102540801?s=20

In this thread you can better see the kind of trick I use:
https://twitter.com/DavidGlaude/status/1370504218445025280?s=20

I split the bust in two with a "Butterfly": https://www.tindie.com/products/8086net/butterfly/ and then the other board I use does have I2C Pull-Up. It would also be possible to make a special Pull-Up board, or solder some resistor directly on your hardware.

**Comment by pierreyvesbaloche** [comment]
That's great advices!
Thank you so much David for all these explanations. Really appreciated.

**Comment by dglaude** [comment]
Tricks explained.
